raw <- tibble::tribble(
             ~pipeline,            ~type,     ~brand,           ~geno, ~Calidad.de.grano, ~Fusarium.sp, ~Pudrición.de.mazorca.mix, ~Pudrición.de.tallo, ~Mancha.de.asfalto, ~Cercospora,
     "ME3 - Subtropic", "STANDARD_WHITE",   "ASGROW",    "ARMADILLO",                NA,           NA,                        NA,                  5L,                 NA,          3L,
     "ME3 - Subtropic", "STANDARD_WHITE",   "ASGROW",  "RINOCERONTE",                NA,           NA,                        NA,                  NA,                 NA,          2L,
     "ME3 - Subtropic", "STANDARD_WHITE",   "ASGROW",   "HIPOPOTAMO",                NA,           NA,                        NA,                  NA,                 NA,          2L,
     "ME3 - Subtropic", "STANDARD_WHITE",   "DEKALB",       "DK4050",                NA,           NA,                        NA,                  NA,                 NA,          2L,
     "ME3 - Subtropic", "STANDARD_WHITE",   "DEKALB",       "DK5021",                NA,           NA,                        NA,                  NA,                 NA,          NA,
     "ME3 - Subtropic", "STANDARD_WHITE",   "DEKALB",       "DK2048",                NA,           NA,                        NA,                  NA,                 NA,          2L,
     "ME3 - Subtropic", "STANDARD_WHITE",   "DEKALB",       "DK4055",                NA,           NA,                        NA,                  NA,                 NA,          2L,
     "ME3 - Subtropic",      "BRACHYTIC",   "ASGROW",       "DELFIN",                NA,           NA,                        NA,                  NA,                 NA,          2L,
  "ME2 - MID_ALTITUDE", "STANDARD_WHITE",   "ASGROW",     "ANTILOPE",                2L,           5L,                        2L,                 55L,                 4L,          4L,
  "ME2 - MID_ALTITUDE", "STANDARD_WHITE",   "ASGROW",     "CAMALEON",                2L,           4L,                        8L,                 51L,                 4L,          4L,
  "ME2 - MID_ALTITUDE", "STANDARD_WHITE",   "DEKALB",       "DK4018",                2L,           4L,                        6L,                 37L,                 5L,          4L,
  "ME2 - MID_ALTITUDE", "STANDARD_WHITE",   "DEKALB",       "DK4021",                2L,           4L,                        4L,                 30L,                 5L,          4L,
  "ME2 - MID_ALTITUDE", "STANDARD_WHITE",         NA,     "BERRENDO",                3L,           4L,                        2L,                 36L,                 4L,          3L,
  "ME2 - MID_ALTITUDE", "STANDARD_WHITE",   "DEKALB",       "DK2037",                3L,           4L,                        3L,                 44L,                 5L,          4L,
  "ME2 - MID_ALTITUDE", "STANDARD_WHITE",   "ASGROW",   "SALAMANDRA",                3L,           3L,                        4L,                 46L,                 4L,          3L,
  "ME2 - MID_ALTITUDE", "STANDARD_WHITE",   "DEKALB",       "DK2069",                NA,           5L,                        6L,                 51L,                 4L,          4L,
  "ME2 - MID_ALTITUDE", "STANDARD_WHITE",   "DEKALB",       "DK2061",                NA,           5L,                        5L,                 56L,                 4L,          4L,
  "ME2 - MID_ALTITUDE",         "YELLOW",   "ASGROW",    "ANTILOPEY",                1L,           5L,                        3L,                 50L,                 4L,          5L,
  "ME2 - MID_ALTITUDE",         "YELLOW",   "DEKALB",      "DK4020Y",                1L,           5L,                        3L,                 50L,                 5L,          4L,
  "ME2 - MID_ALTITUDE",          "EARLY",   "ASGROW",     "TIGRILLO",                2L,           5L,                        4L,                 35L,                 5L,          4L,
  "ME2 - MID_ALTITUDE",          "EARLY",   "ASGROW",      "OCELOTE",                2L,           6L,                        4L,                 51L,                 5L,          3L,
  "ME2 - MID_ALTITUDE",       "MID_TIER",   "DEKALB", "DK2027/CRM77",                2L,           3L,                        6L,                 38L,                 5L,          4L,
  "ME2 - MID_ALTITUDE",       "MID_TIER",         NA,        "CB100",                3L,           4L,                        9L,                 50L,                 4L,          4L,
  "ME2 - MID_ALTITUDE",       "MID_TIER",         NA,        "CRM28",                3L,           3L,                        NA,                  NA,                 4L,          NA,
        "ME3 - TROPIC", "STANDARD_WHITE",   "DEKALB",        "DK457",                2L,           NA,                        7L,                  5L,                 4L,          NA,
        "ME3 - TROPIC", "STANDARD_WHITE",   "DEKALB",        "DK390",                2L,           6L,                        5L,                 17L,                 3L,          NA,
        "ME3 - TROPIC", "STANDARD_WHITE",   "DEKALB",        "DK357",                2L,           6L,                       13L,                  NA,                 6L,          NA,
        "ME3 - TROPIC", "STANDARD_WHITE",   "DEKALB",       "DK6018",                2L,           4L,                        7L,                  5L,                 4L,          NA,
        "ME3 - TROPIC", "STANDARD_WHITE",   "DEKALB",       "DK6021",                5L,           NA,                       10L,                  NA,                 5L,          NA,
        "ME3 - TROPIC", "STANDARD_WHITE", "MONSANTO",       "MU9089",                2L,           5L,                       10L,                  NA,                 6L,          NA,
        "ME3 - TROPIC",       "MID_TIER", "MONSANTO",       "MV9012",                2L,           5L,                        8L,                 12L,                 5L,          NA,
        "ME3 - TROPIC",         "YELLOW",   "DEKALB",       "DK7088",                2L,           3L,                        7L,                  5L,                 4L,          NA,
        "ME3 - TROPIC",         "YELLOW",   "DEKALB",       "DK7500",                2L,           NA,                        7L,                  5L,                 5L,          NA,
        "ME3 - TROPIC",         "YELLOW",   "DEKALB",       "DK7508",                2L,           NA,                        7L,                  5L,                 4L,          NA,
        "ME3 - TROPIC",         "YELLOW",   "DEKALB",       "DK8719",                2L,           5L,                        9L,                  8L,                 6L,          NA
  )
